#!/usr/bin/env sh

# prelude
# git clone --bare https://github.com/je-al/dotfiles.git .yadm/repo.git
# git --git-dir .yadm/repo.git --work-tree . checkout

cd $HOME

echo "init submodules"
git --git-dir .yadm/repo.git --work-tree . submodule update --recursive --init

echo "fix git repo config"
git --git-dir .yadm/repo.git config core.bare false
git --git-dir .yadm/repo.git config core.worktree $HOME
git --git-dir .yadm/repo.git config core.sharedrepository 0600
git --git-dir .yadm/repo.git config receive.denyNonFastforwards true
git --git-dir .yadm/repo.git config status.showUntrackedFiles no
git --git-dir .yadm/repo.git config yadm.managed true

echo "temporary path addition"
PATH="$HOME/.local/bin:$PATH"

echo "updating the yadm repo origin URL"
yadm remote set-url origin "git@github.com:je-al/dotfiles.git"

echo "installing fonts"
$HOME/.misc/fonts/install.sh

echo "done!"
